# Site settings
title: Melt Ice Cream
email: christiana@meltsalem.com
description: > # this means to ignore newlines until "baseurl:"
  Melt Ice Cream homemade ice cream
baseurl: "" # the subpath of your site, e.g. /blog
url: https://meltsalem.com # the base hostname & protocol for your site

# Build settings
gems:
  - jekyll-assets
exclude:
  - bin
  - bower_components
  - bower.json
  - Gemfile
  - Gemfile.lock
markdown: kramdown
timezone: US/Eastern
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
