# Site settings
title: Melt Ice Cream
email: christiana@meltsalem.com
description: Homemade ice cream made on-site in Salem, MA. Bold innovative flavors, exceptional customer service, local ingredients.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://meltsalem.com # the base hostname & protocol for your site

# Build settings
gems:
  - jekyll-assets
exclude:
  - bin
  - bower_components
  - bower.json
  - Gemfile
  - Gemfile.lock
markdown: kramdown
timezone: US/Eastern
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
contentful:
  spaces:
    - authors: # Jekyll _data folder identifier - Required
        space: 37yop5vw50a1
        access_token: 1d19ff9eb08cb9db6b49c57d387904edeea0e4d7904e9a13be9b1e0850576fbf
        cda_query:
          content_type: '1kUEViTN4EmGiEaaeC6ouY'
    - categories: # Jekyll _data folder identifier - Required
        space: 37yop5vw50a1
        access_token: 1d19ff9eb08cb9db6b49c57d387904edeea0e4d7904e9a13be9b1e0850576fbf
        cda_query:
          content_type: '5KMiN6YPvi42icqAUQMCQe'
    - posts: # Jekyll _data folder identifier - Required
        space: 37yop5vw50a1
        access_token: 1d19ff9eb08cb9db6b49c57d387904edeea0e4d7904e9a13be9b1e0850576fbf
        cda_query:
          content_type: '2wKn6yEnZewu2SCCkus4as'
page_gen-dirs: true
page_gen:
  - data: 'contentful.spaces.posts'
    template: 'post'
    name: 'slug'
    dir: 'posts'
  - data: 'contentful.spaces.authors'
    template: 'default'
    name: 'name'
    dir: 'authors'
