# Site settings
title: Melt Ice Cream
email: christiana@meltsalem.com
description: Homemade ice cream made on-site in Salem, MA. Bold innovative flavors, exceptional customer service, local ingredients.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://meltsalem.com # the base hostname & protocol for your site

# Build settings
gems:
  - jekyll-assets
exclude:
  - bin
  - contentful_env
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - README.md
  - yarn.lock
markdown: kramdown
timezone: US/Eastern
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
contentful:
  spaces:
    - home_page: # Jekyll _data folder identifier - Required
        space: ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN
        cda_query:
          content_type: 'homePage'
